name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        perl: [
          '5.8',
          '5.10', '5.12', '5.14', '5.16', '5.18',
          '5.20', '5.22', '5.24', '5.26', '5.28',
          '5.30', '5.32', '5.34', '5.36', '5.38',
          '5.40', '5.42',
        ]

    runs-on: ubuntu-latest

    name: Perl ${{ matrix.perl }}

    steps:
      - uses: actions/checkout@v4

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - run: perl Makefile.PL

      - run: cpanm --installdeps --notest .

      # Upgrade Test::More on really old perls for subtest support.
      #- run: cpanm --notest --skip-satisfied Test::More~0.94

      - run: make test
